service:
  name: starwars-api-lambda

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  main:
    handler: src/index.handler
    events:
      - http:
          method: any
          path: /{any+}